=== maxmelnyk/task13_XML/XML/src/main/resources/xml/gemXSD.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="gems"
  xmlns="gems"
  elementFormDefault="qualified">

  <xs:element name="gems">
    <xs:complexType>
      <xs:sequence>
        <xs:element name='gem' type='gemType' minOccurs='0' maxOccurs='unbounded'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:complexType name="gemType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="preciousness" type="xs:string"/>
      <xs:element name="origin" type="xs:string"/>
      <xs:element name="visualParameters">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="transparency">
              <xs:simpleType>
                <xs:restriction base="xs:decimal">
                  <xs:fractionDigits value="100"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
            <xs:element name="wayOfCutting">
              <xs:simpleType>
                <xs:restriction base="xs:decimal">
                  <xs:minInclusive value="4"/>
                  <xs:maxInclusive value="15"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="value" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name='gemID' type='xs:integer'/>
  </xs:complexType>
</xs:schema>

=== maxmelnyk/task13_XML/XML/src/main/resources/xml/gem.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="gemXSLT.xsl"?>

<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="gemXSD.xsd">

  <gem gemID="0">
    <name>Ruby</name>
    <preciousness>precious</preciousness>
    <origin>Asia</origin>
    <visualParameters>
      <color>red</color>
      <transparency>80</transparency>
      <wayOfCutting>9</wayOfCutting>
    </visualParameters>
    <value>1</value>
  </gem>

  <gem gemID="1">
    <name>Diamond</name>
    <preciousness>precious</preciousness>
    <origin>Africa</origin>
    <visualParameters>
      <color>white</color>
      <transparency>100</transparency>
      <wayOfCutting>15</wayOfCutting>
    </visualParameters>
    <value>5</value>
  </gem>

  <gem gemID="2">
    <name>Diamond</name>
    <preciousness>precious</preciousness>
    <origin>Africa</origin>
    <visualParameters>
      <color>yellow</color>
      <transparency>85</transparency>
      <wayOfCutting>8</wayOfCutting>
    </visualParameters>
    <value>3</value>
  </gem>

  <gem gemID="3">
    <name>Zirconium</name>
    <preciousness>semi precious</preciousness>
    <origin>India</origin>
    <visualParameters>
      <color>yellow</color>
      <transparency>90</transparency>
      <wayOfCutting>9</wayOfCutting>
    </visualParameters>
    <value>1</value>
  </gem>
</gems>
